### ISSUE TITLE
Project pages do not open if images are not loaded

### ISSUE THREAD

**Issue by mietcls** [opensummerofcode/website#140]
The pictures take a long time to load; and prevents you from clicking on the projects themselves: https://osoc.be/editions/2020.

Happens in Chrome and Safari on a MacBook Pro 2020. Fast internet, so not an exception.

**Comment by MichielLeyman** [comment]
I suspect this is due to our switch to prerendering this page (when we switched to Netlify) as opposed to server rendering it. The images have been optimized so it's not a size/optimization issue, there are just too many of them.

I'll make a PR that lazy loads them which should resolve the time to interactive issue

**Comment by mietcls** [comment]
Wonderful! Thank you <3
